clc;clear all;close all  %demo for pmlda

addpath support/lightspeed         % install lightspeed toolbox and add to your path
addpath support

%%loading picture

ori_image=imread('sunset2.jpg'); % read sunset image
doc_size_width=160;
doc_size_length=160;
%%
% feature extracted using 
load 'superpixel.mat' % generated by normalized cut
load 'feature.mat' %feature extracted



%% document -> superpixel (construction)

maxim_spx=max(superpixel(:));
minim_spx=min(superpixel(:));
feature=feature'*255;
for i=minim_spx:maxim_spx
    Data{i}.X=feature((superpixel(:)==i),:);
end 

%% run PMLDA
% PMLDA parameter
para.topic=3;    % number of topics
para.alpha=ones(1,para.topic);    % Prior for topic proportion pi
para.exp=0.5;          % 1/para.exp = expectation of the scaling factor s
para.iter=100;       % number of iterations for Gibbs sampling
para.muStep=eye(3);  % variance of the proposal distribution for cluster means

[samples,cluster]=pmlda_leastsquare(Data,para) %PMLDA with least square

%>>>> Uncomment to switch to gibbs sampling method <<<<%
%[samples,cluster]=pmlda_gibbs(Data,para) % PMLDA with gibbs sampling %%%

%% superpixel -> document (reconstruction)
unordered_result=[];
for i = 1:length(samples)
unordered_result=[unordered_result;samples(i).zStar];
end

unordered_result=unordered_result';
ordered_result = zeros(para.topic,doc_size_width*doc_size_length);
for j=1:para.topic
    count1=0;
    for i=minim_spx:maxim_spx
        count2=count1+sum(superpixel(:)==i); 
        ordered_result(j,(superpixel(:)==i))=unordered_result(j,(count1+1):count2);
        count1=count2;
    end
end


%% Visualize the result
figure;
subplot(1,2,1);title('Real image') % visualization of image input
imshow(ori_image);
subplot(1,2,2);title('Superpixels') % visualization of superpixel
imagesc(reshape(superpixel,[doc_size_width,doc_size_length]));
figure;
for i=1:para.topic % visualization of topic membership
subplot(1,para.topic,i);title(['Topic ',num2str(para.topic)]);
imagesc(reshape(ordered_result(i,:),[doc_size_width,doc_size_length]));
end




